### PR TITLE
Docs: document org-capture issue

### PR DESCRIPTION
**Pull request by benoitj**
Hi Adam, 

as discussed, here is the solution to an issue encountered while using yequake / org-capture.

thanks!

Benoit

### CODE REVIEW

**Comment by alphapapa** [comment]
Thank you!

**Comment by alphapapa** [comment]
@benoitj Apologies for not merging this sooner.  Since you deleted your fork, GitHub won't let me reopen this PR.  I'll move it to a new one...

**Comment by benoitj** [comment]
No worries, was doing a cleanup of my forks yesterday and deleted it. 

sorry for the inconvenience.

**Comment by alphapapa** [comment]
No problem.  :)

**Pull request closed without merging**
